export const SOCKET_MODULE = 'SocketModule';

export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET';

export const GET_DIRECTORIES = 'GET_DIRECTORIES';
export const GET_DIRECTORIES_SUCCESS = 'GET_DIRECTORIES_SUCCESS';
export const GET_DIRECTORIES_ERROR = 'GET_DIRECTORIES_ERROR';

export const UPDATE_DIRECTORIES = 'UPDATE_DIRECTORIES';
